apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: edge-routers
spec:
  deploymentPlan:
    role: edge
    placement: AntiAffinity
  edgeConnectors:  
    - host: cloud1-router-mesh.cluster-1.svc
      port: 45672
      name: cloud1-edge-connector
    - host: cloud2-router-mesh.cluster-2.svc
      port: 45672
      name: cloud2-edge-connector