kind: ConfigMap
apiVersion: v1
metadata:
  name: config-br-defaults
  namespace: knative-eventing
data:
  default-br-config: |
    clusterDefault:
      brokerClass: MTChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-kafka-channel
      namespace: knative-eventing
    namespaceDefaults:
      newco-tenant:
        apiVersion: v1
        kind: ConfigMap
        name: config-imc-channel
        namespace: newco-tenant
      important-tenant:
        apiVersion: v1
        kind: ConfigMap
        name: config-important-tenant-channel
        namespace: important-tenant 