apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  labels:
    camel.apache.org/generation: "1"
    camel.apache.org/integration: camel-kamqp-mediator2
  name: testing-dbevents-camel-kamqp-mediator2
  namespace: cloud-1
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: testing-dbevents
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: camel-kamqp-mediator2
      namespace: cloud-1
